# Deployment for vault instance 1
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        instance: vault-1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vault
          image: "drud/vault:0.6.2"
          imagePullPolicy: Always
          ports:
          - containerPort: 8200
            name: main-port
          - containerPort: 8201
            name: local-talk-port
          env:
          - name: VAULT_CONSUL_KEY
            valueFrom:
              secretKeyRef:
                name: vault-consul-key
                key: consul-key
          - name: VAULT_LOCAL_CONFIG
            # Disable registration as we don't even use consul's service discovery features
            # Port 9000 listener is for local and status checks
            # See https://github.com/hashicorp/vault/issues/1559 for why true is quoted in disable_registration
            value:
                backend "consul" {
                  address = "$(CONSUL_HTTP_SERVICE_HOST):$(CONSUL_HTTP_SERVICE_PORT)"
                  cluster_addr = "https://$(VAULT_1_SERVICE_HOST):$(VAULT_1_SERVICE_PORT_BACKENDPORT)"
                  token = "$VAULT_CONSUL_KEY"
                  disable_registration = "true"
                }
                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_cert_file = "/etc/tls/tls.crt"
                  tls_key_file = "/etc/tls/tls.key"
                }
                listener "tcp" {
                  address = "0.0.0.0:9000"
                  tls_disable = 1
                }
                disable_mlock = true
          # VAULT_ADDR is provided only for convenience - so don't have to set when logging in.
          - name: VAULT_ADDR
            value: http://localhost:9000
          readinessProbe:
            httpGet:
              # "leader" returns a 503 for a sealed vault, which is basically what we want
              path: /v1/sys/leader
              port: 9000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
              # name must match the volume name below
              - name: "tls"
                mountPath: /etc/tls
              - name: log-storage
                mountPath: /vault/logs
        - name: logging-sidecar
          image: drud/fluentd_logging_sidecar:1.4
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          env:
          - name: FILES_TO_COLLECT
            value: "/mnt/log/audit.log"
          - name: FILES_FORMAT
            value: json
          volumeMounts:
            - name: log-storage
              readOnly: true
              mountPath: /mnt/log
      volumes:
        - name: "tls"
          "secret": {
            "secretName": "vaulttls"
          }
        - name: log-storage
          emptyDir: {}

---
